#Variables 
CHOIX_DE_LA_BOX         ="debian/jessie64"
NOM_DE_LA_MACHINE       ="Runners-Gitlab-VM"
IP_DE_LA_MACHINE        ="192.168.206.45"
MASQUE_DE_SOUS_RESEAU   ="255.255.255.128"

#Variable reglage VM
RAM_VM                  ="6144"
NOMBRE_COEUR_VM         =2

#Variables reglage serveur Gitlab
URL_GITLAB              ="http://192.168.206.44/"
TOKEN_GITLAB            ="tRrb9y2C3EzqA4HzaxNr"

Vagrant.configure("2") do |config|
  #Choix de la box a utiliser
  config.vm.box = CHOIX_DE_LA_BOX
  
  #Parametrage du réseau en bridge depuis la carte "enp3s0"
  config.vm.network :public_network, :bridge => "enp3s0", ip: IP_DE_LA_MACHINE, :netmask => MASQUE_DE_SOUS_RESEAU
  
  #Nom de la machine dans Vagrant
  config.vm.define NOM_DE_LA_MACHINE
  
  #Autoriser la connection avec mot de passe en ssh ( user/password : vagrant/vagrant ) 
  config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
    
  # Configuration de la VM
  config.vm.provider "virtualbox" do |vb|
    # Desactiver l'interface
    vb.gui = false
    # Montant de ram et nombre de coeurs à allouer
    vb.memory = RAM_VM
    vb.cpus = NOMBRE_COEUR_VM
  end
    
  ###### PROVISION DE ANSIBLE ######
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/playbook.yml"
    ansible.verbose = true
    ansible.extra_vars = {
    token: TOKEN_GITLAB,
    url: URL_GITLAB
  }
  
end

end