CHOIX_DE_LA_BOX         ="debian/jessie64"
NOM_DE_LA_MACHINE       ="Machine-test"
IP_DE_LA_MACHINE        ="192.168.206.34"
MASQUE_DE_SOUS_RESEAU   ="255.255.255.128"

Vagrant.configure("2") do |config|

config.vm.box = CHOIX_DE_LA_BOX
config.vm.define NOM_DE_LA_MACHINE

config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"

config.vm.network :public_network, :bridge => "enp3s0: Ethernet", ip: IP_DE_LA_MACHINE, :netmask => MASQUE_DE_SOUS_RESEAU
 



###### PROVISION DE ANSIBLE ######
config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "provision/playbook.yml"
  ansible.verbose = true
  ansible.install = true
  ansible.install_mode = "apt"
end
end
