# -*- mode: ruby -*-
# vi: set ft=ruby :

IP_GITLAB               ="gitlab.com"
TOKEN_GITLAB            ="g-zjfRwfqVWwfvGsrYDh"

Vagrant.configure("2") do |config|
  # Box Debian 8 Jessie 64
  config.vm.box = "debian/jessie64"
  # Fixe l'adresse ip de la VM (changer le ip par une disppnible)
  config.vm.network :public_network, :bridge => "enp3s0: Ethernet", ip: "192.168.206.30", :netmask => "255.255.255.128"
  # Nom de la VM
  config.vm.define "Jessie"

  ###### PROVISION DE ANSIBLE ######
config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "provision/playbook.yml"
  ansible.verbose = true
  ansible.install = true
  ansible.install_mode = "apt"

  ansible.extra_vars = {
    ip: IP_GITLAB, 
    token: TOKEN_GITLAB
  }

end

end
